apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-gke
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld-gke
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---